# Generated by Django 4.2.3 on 2023-08-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Maceta',
                'verbose_name_plural': 'Macetas',
            },
        ),
        migrations.AlterModelOptions(
            name='decoracion',
            options={'ordering': ['-tipo'], 'verbose_name': 'Decoracion', 'verbose_name_plural': 'Decoracion'},
        ),
        migrations.AlterModelOptions(
            name='jardineria',
            options={'ordering': ['-tipo'], 'verbose_name': 'Jardineria', 'verbose_name_plural': 'Jardineria'},
        ),
        migrations.AlterModelOptions(
            name='plantas',
            options={'ordering': ['-genero'], 'verbose_name': 'Planta', 'verbose_name_plural': 'Plantas'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='decoracion',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='jardineria',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='plantas',
            old_name='Precio',
            new_name='precio',
        ),
    ]
